# fly.toml app configuration file generated for flintapi-gateway on 2025-11-16T02:55:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flintapi-gateway'
primary_region = 'lhr'

[build]
  dockerfile = './api.Dockerfile'

[env]
  PORT = '9999'

[http_service]
  internal_port = 9999
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
