# fly.toml app configuration file generated for ramp-service on 2025-11-15T10:50:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ramp-service'
primary_region = 'lhr'

[build]
  dockerfile = './ramp.Dockerfile'

[env]
  PORT = '9999'

[http_service]
  internal_port = 9990
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
