# fly.toml app configuration file generated for flintapi-softhsm on 2025-10-07T03:20:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kms-service'
primary_region = 'lhr'

[build]
  dockerfile = './kms.Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  PKCS11_MODULE_PATH = '/usr/lib/softhsm/libsofthsm2.so'
  SOFTHSM2_CONF = '/var/lib/softhsm/softhsm2.conf'

[[mounts]]
  source = 'softhsm_tokens'
  destination = '/var/lib/softhsm'
  initial_size = '1gb'

# [http_service]
#   internal_port = 2345
#   force_https = true
#   auto_stop_machines = 'stop'
#   auto_start_machines = true
#   min_machines_running = 0
#   processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 2345
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  ports = []

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

# [[metrics]]
#   port = 9091
#   path = '/metrics'
