name: kms-service
on:
  push:
    branches:
      - main
    paths:
      - services/kms/**
      - packages/shared/**
  pull_request:
    branches:
      - main
    paths:
      - services/kms/**
      - packages/shared/**

env:
  NODE_ENV: production
  PORT: 9999

concurrency:
  group: deploy-kms
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploys kms service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - run: pnpm run deploy:kms
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
