name: ramp-service
on:
  push:
    branches:
      - main
    paths:
      - services/ramp/**
      - packages/shared/**
  pull_request:
    branches:
      - main
    paths:
      - services/ramp/**
      - packages/shared/**

env:
  NODE_ENV: production
  PORT: 9999

jobs:
  deploy:
    name: Deploys ramp service
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - run: pnpm run deploy:ramp
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
